### ISSUE TITLE
Doesn't work on AS 4.0.1

### ISSUE THREAD

**Issue by RJSDevel** [Ghedeon/ADB-Uninstall#12]
2020-09-29 22:20:53,309 [ 301132]  ERROR - intellij.openapi.progress.Task - org.jetbrains.android.facet.AndroidFacet.getAndroidModel()Lcom/android/tools/idea/model/AndroidModel; 
java.lang.NoSuchMethodError: org.jetbrains.android.facet.AndroidFacet.getAndroidModel()Lcom/android/tools/idea/model/AndroidModel;
	at com.vv.adbuninstall.UninstallAction.uninstallFromDevices(UninstallAction.java:95)
	at com.vv.adbuninstall.UninstallAction.access$100(UninstallAction.java:50)
	at com.vv.adbuninstall.UninstallAction$1.run(UninstallAction.java:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-29 22:20:53,310 [ 301133]  ERROR - intellij.openapi.progress.Task - Android Studio 4.0.1  Build #AI-193.6911.18.40.6626763 
2020-09-29 22:20:53,310 [ 301133]  ERROR - intellij.openapi.progress.Task - JDK: 1.8.0_242-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-09-29 22:20:53,310 [ 301133]  ERROR - intellij.openapi.progress.Task - OS: Windows 7 
2020-09-29 22:20:53,310 [ 301133]  ERROR - intellij.openapi.progress.Task - Plugin to blame: ADB Uninstall version: 1.1.3 
2020-09-29 22:20:53,311 [ 301134]  ERROR - intellij.openapi.progress.Task - Last Action: ADB Uninstall 
2020-09-29 22:21:07,487 [ 315310]  ERROR - intellij.openapi.progress.Task - org.jetbrains.android.facet.AndroidFacet.getAndroidModel()Lcom/android/tools/idea/model/AndroidModel; 
java.lang.NoSuchMethodError: org.jetbrains.android.facet.AndroidFacet.getAndroidModel()Lcom/android/tools/idea/model/AndroidModel;
	at com.vv.adbuninstall.UninstallAction.uninstallFromDevices(UninstallAction.java:95)
	at com.vv.adbuninstall.UninstallAction.access$100(UninstallAction.java:50)
	at com.vv.adbuninstall.UninstallAction$1.run(UninstallAction.java:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-29 22:21:07,488 [ 315311]  ERROR - intellij.openapi.progress.Task - Android Studio 4.0.1  Build #AI-193.6911.18.40.6626763 
2020-09-29 22:21:07,488 [ 315311]  ERROR - intellij.openapi.progress.Task - JDK: 1.8.0_242-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-09-29 22:21:07,488 [ 315311]  ERROR - intellij.openapi.progress.Task - OS: Windows 7 
2020-09-29 22:21:07,488 [ 315311]  ERROR - intellij.openapi.progress.Task - Plugin to blame: ADB Uninstall version: 1.1.3 
2020-09-29 22:21:07,489 [ 315312]  ERROR - intellij.openapi.progress.Task - Last Action: ADB Uninstall 
2020-09-29 22:21:08,308 [ 316131]   INFO - rationStore.ComponentStoreImpl - Saving Project (name=ConnectionService, containerState=ACTIVE, componentStore=C:\Users\Developer\AndroidStudioProjects\ConnectionService) KotlinCommonCompilerArguments took 11 ms, libraryTable took 15 ms
